services:
  - type: web
    name: lakeside-retreat-production
    repo: https://github.com/Lakesideglamping/lakeside-retreat-staging
    branch: main
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run start:production
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET  
        sync: false
      - key: UPLISTING_API_KEY
        sync: false
      - key: UPLISTING_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ADMIN_USERNAME
        value: admin
      - key: BCRYPT_ROUNDS
        value: 12
      - key: LOGIN_RATE_LIMIT_ATTEMPTS
        value: 5
      - key: LOGIN_RATE_LIMIT_WINDOW_MINUTES
        value: 15
      - key: GENERAL_RATE_LIMIT_REQUESTS
        value: 100
      - key: GENERAL_RATE_LIMIT_WINDOW_MINUTES
        value: 15
